name: Check for broken links
on:
  push:
  schedule:
    - cron: '0 22 * * 0'

jobs:
  check:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Install
      run: |
        sudo apt-get update -q
        sudo apt-get install -y linkchecker
    - name: Wait for publish to complete
      run: |
        sleep 60
    - name: Check
      run: |
        linkchecker www.budgetwithbuckets.com --no-status --check-extern --timeout=10
